services:
  db:

    #using the latest postgresSQL Image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
       POSTGRES_PASSWORD: 1215

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"